server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, configprops, metrics
